# Generated by Django 4.2.7 on 2023-11-08 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_name', models.CharField(max_length=30, verbose_name='First name ')),
                ('user_lastname', models.CharField(max_length=30, verbose_name='Last name ')),
                ('user_age', models.IntegerField(verbose_name='Age ')),
                ('user_workplace', models.CharField(max_length=30, verbose_name='Enter your work place ')),
                ('user_email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
