# Generated by Django 4.2.7 on 2023-11-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='user_age',
        ),
        migrations.RemoveField(
            model_name='register',
            name='user_workplace',
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
